s-xix98/trc-prot

- backend/.env
- backend/package-lock.json
- backend/package.json
- backend/prisma/schema.prisma
- docker-compose.yml
- log/backend-log.md
> Init prisma

- backend/package-lock.json
- backend/package.json
- backend/src/main.ts
- log/backend-log.md
> Init swagger

- backend/prisma/schema.prisma
- backend/src/app.module.ts
- backend/src/post-message/dto/message.dto.ts
- backend/src/post-message/post-message.controller.ts
- backend/src/post-message/post-message.module.ts
- backend/src/post-message/post-message.service.ts
- backend/src/prisma/prisma.module.ts
- docker-compose.yml
> /post-messageへのPOSTでdbにレコードを追加できるようにする

- frontend/src/features/chat/ChatInput.tsx
- frontend/src/features/chat/ChatTalkArea.tsx
> 文字が入力されるたびに全体が再レンダリングされないように直してあげた

- README.md
README に 開発時などにアクセスする uri を 書いた
> README に 開発時などにアクセスする uri を 書いた

- frontend/src/components/Footer/Footer.tsx
- frontend/src/components/Header/Header.tsx
- frontend/src/components/Layout/MainLayout.tsx
> ヘッダーとフッターを別コンポーネントに分けた

- frontend/src/components/Footer/Footer.stories.tsx
- frontend/src/components/Header/Header.stories.tsx
- frontend/src/components/Header/Header.tsx
> ヘッダーに開発時に使うurlを追記

- backend/src/main.ts
- フロントエンドから api を投げる際にエラーが発生したので下記を設定
- [CORS | NestJS - A progressive Node.js framework](https://docs.nestjs.com/security/cors)
> フロントエンドから api を投げる際にエラーが発生したので cors を設定

- frontend/.eslintrc.cjs
- frontend/package-lock.json
- frontend/package.json
- frontend/src/features/chat/Chat.tsx
- log/frontend-log.md
> 70 eslint で import の 順番チェックする

- backend/prisma/user_seed.ts
存在しないならcreate
存在したらupdate(何もしない)
https://www.prisma.io/docs/concepts/components/prisma-client/crud
close #81
> ダミーユーザーが存在しない時にcreateするようにした

- Makefile
- frontend/.storybook/test-runner.js
- frontend/Dockerfile
- frontend/Makefile
- frontend/package-lock.json
- frontend/package.json
- log/frontend-log.md
- 下の記事とか見ながら読んで欲しいます
- `make sb-test` で 実行
- #90 で 現在の スナップショット を追加
- ref
- [Interaction tests](https://storybook.js.org/docs/react/writing-tests/interaction-testing)
- [Storybook 単体でインタラクションテストを実施する](https://zenn.dev/azukiazusa/articles/storybook-interaction-testing)
- playwright
- [Fast and reliable end-to-end testing for modern web apps | Playwright](https://playwright.dev/)
- [Playwrightも知らないで開発してる君たちへ - Qiita](https://qiita.com/cc822jp/items/6f786a9ed104af1a382f)
> 88 storybook を 使って UI テスト

- backend/src/app.module.ts
- backend/src/user/dto/signUp.dto.ts
- backend/src/user/user.controller.spec.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.spec.ts
- backend/src/user/user.service.ts
- log/backend-log.md
<host port>/user/signup POSTにdtoに型を合わせてJSONを送ることでユーザーの作成が可能にした
> 91 userのsignupのエンドポイント作成

- frontend/src/components/Elements/Button/BasicButton.tsx
- frontend/src/features/chat/ChatInput.tsx
- frontend/src/features/chat/ChatTalkArea.tsx
- frontend/src/features/chat/ChatTalkAreaHeader.tsx
client idを発言者名にしてるから、socketが変わると発言者も変わるけど後で直す
> historyの再取得ボタンをつけた

- frontend/.eslintrc.cjs
- frontend/src/App.tsx
- frontend/src/components/Elements/Input/Input.tsx
- frontend/src/features/chat/components/Chat.tsx
- frontend/src/features/chat/components/ChatHistory.tsx
- frontend/src/features/chat/components/ChatInput.tsx
- frontend/src/features/chat/components/ChatTalkArea.tsx
- frontend/src/main.tsx
- frontend/src/stories/Header.stories.ts
- log/frontend-log.md
- import 順番 の 変更
- import グループごとに 改行をつける
- '@/features' からの import 抑制
> frontend eslint の 設定を 更新

- backend/.eslintrc.js
- backend/src/app.controller.spec.ts
- backend/src/app.controller.ts
- backend/src/app.module.ts
- backend/src/events/events.gateway.spec.ts
- backend/src/events/events.module.ts
- backend/src/main.ts
- backend/src/post-message/post-message.controller.spec.ts
- backend/src/post-message/post-message.controller.ts
- backend/src/post-message/post-message.module.ts
- backend/src/post-message/post-message.service.spec.ts
- backend/src/post-message/post-message.service.ts
- backend/src/prisma/prisma.module.ts
- backend/src/prisma/prisma.service.spec.ts
- backend/src/user/user.controller.spec.ts
- backend/src/user/user.controller.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.spec.ts
- backend/src/user/user.service.ts
- backend/test/app.e2e-spec.ts
[import で グループごとに改行を入れる ようにした](https://github.com/s-xix98/trc-prot/commit/93acae29b29a4857b0990aa414de49b681de0d4e)
> 125 backend の eslint の 設定を更新

- .github/workflows/check-build.yml
- backend/Makefile
- frontend/Makefile
問題なく build 出来るかを チェックする github action を 追加したます
> build 出来るかを チェックする github action を追加

- backend/nest-cli.json
- backend/src/user/dto/user.dto.ts
- backend/src/user/user.controller.ts
swaggerでlogin,signupからリクエストを送るときにデフォルト値を入れるようにした
参考にした
https://docs.nestjs.com/openapi/operations
close #138
> swaggerで試しリクエスト送る時のデフォルトパラメーターを設定した

- backend/prisma/user_seed.ts
- backend/src/main.ts
- backend/src/post-message/dto/message.dto.ts
- backend/src/post-message/post-message.controller.ts
- backend/src/user/dto/user.dto.ts
dbに追加するデフォルトダミーデータの初期値をわかりやすくした
swagger guiのpost-messag試しリクエストのデフォルトパラメーターを設定した。
パスワードはnickname * 2にした
> 151 swagger の ユーザー 名とか パスワードが わかりにくい ので わかりやすく

- frontend/doc/jotai.md
- frontend/package-lock.json
- frontend/package.json
- frontend/src/App.tsx
- frontend/src/features/user/components/user.tsx
- jotai
- [GitHub - pmndrs/jotai: 👻 Primitive and flexible state management for React](https://github.com/pmndrs/jotai)
- [Jotai, primitive and flexible state management for React](https://jotai.org/)
- 参考リンクとか
-  [React 用状態管理ライブラリ「Jotai」に入門](https://zenn.dev/kkeeth/articles/studying-jotai-library)
> 164 jotai とかいうやつ 使ってみるます

- backend/prisma/schema.prisma
prisuserテーブルのemailとhashedpasswordが隣になるようにした
> userテーブルのemailとhashedpasswordが並ぶようにした

- .github/workflows/storybook-test.yml
- frontend/Makefile
- frontend/scripts/check_storybook_file.sh
- frontend/scripts/create_storybook_file.sh
- storybook の ファイルが あるか 確認する スクリプト 追加
-  storybook の ファイルが ない時に github action で 落ちるようにした
- storybook の ファイルが ない時に 作成する スクリプトを 追加
---
> 180 storybook の ファイルが あるか 確認するない時に ファイル作成するような script を作成

- frontend/src/features/chat/components/Chat.tsx
- frontend/src/features/chat/components/ChatChannelArea.tsx
- frontend/src/features/chat/components/ChatTalkArea.tsx
- frontend/src/features/chat/components/ChatTalkAreaHeader.tsx
チャットルームをクリックしたらクリックしたルームの情報をChatTalkAreaコンポーネントに渡すようにした（現状はチャットルームの情報を取得する機能がないので文字列だけ）
> 197 チャットルームをクリックしたらクリックしたチャットページを表示させるようにする

- backend/src/user/user.service.spec.ts
参考
https://docs.nestjs.com/fundamentals/testing
setupメソッド
https://jestjs.io/ja/docs/api#%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89
expect
https://jestjs.io/ja/docs/expect#expectvalue
toEqual
https://jestjs.io/ja/docs/expect#toequalvalue
reject
https://jestjs.io/ja/docs/expect#rejects
#158 から
> 140 userエンドポイントのテストケースを作る

- docker-compose.yml
- 不要なオプションの削除
- スキーマ更新の強制適用
- サブシェルのスコープミスってたのを修正
> 228 prismaの起動コマンドの修正

- Makefile
- frontend/Makefile
- frontend/package.json
- frontend/src/constants.ts
- frontend/src/features/chat/api/postMessage.ts
- frontend/src/features/user/api/userLogin.ts
- frontend/src/features/user/api/userSignUp.ts
- frontend/src/socket.ts
- フロントエンドコンテナから storybook インタラクションテスト などで、バックエンドコンテナに api などのアクセスできるように
- ローカルのブラウザ では、`http://localhost:8000` でアクセスできる
- フロントエンドコンテナからでは`http://backend:8000` にアクセスする必要がある
- 追加で一つフロントエンドコンテナを立てて、その中で インタラクションテスト を実行できるようにした
- 1 つのコンテナでやるには、環境変数変えて再起動したりする必要ありだと思う
- 動作の確認は下記プルリクで確認して (同じプルリクでも良かったかも)
- #240
> フロントエンドコンテナから storybook インタラクションテスト などで、バックエンドコンテナに api などのアクセスできるように

- .gitignore
- Makefile
- Dockerfile に変更あった時のみ再ビルド
- dockerのbuildがpackage.jsonが変更されるたび走るので、
> Dockerfile に変更あった時のみ再ビルド

- Makefile
- make時にローカルでもnpm i を実行するようにした
> make時にローカルでもnpm i を実行

- .github/workflows/backend-test.yml
新機能を試す必要がないので消した
俺は君たちを試してたけどね
https://www.prisma.io/docs/concepts/components/preview-features/cli-preview-features
> preview-futureが不要なので消した

- Makefile
make時にprismaClient を生成するnpx prisma generateを追記した
> make時にprismaClient更新するようにした

- frontend/src/components/Layout/Container.tsx
- frontend/src/components/Layout/ContainerItem.tsx
> styled-componentsに置き換えた

- Makefile
- docker-compose.yml
- docker-compose.yml の フォーマット修正
- fmt, fmt-ck で docker-compose.yml にも フォーマッター当てるようにしたます
> 292 docker composeyml の フォーマットしたます

- frontend/src/features/game/Game.tsx
- frontend/src/hooks/useCanvas.ts
> 308 ゲームのリファクタ

- frontend/src/app/api/auth/[...nextauth]/route.ts
- frontend/src/app/types/next-auth.d.ts
backendから送られてくる予定のjwtをセットできるようにした
この辺見て設定した
https://zenn.dev/nrikiji/articles/d37393da5ae9bc#%E3%82%A2%E3%82%AF%E3%82%BB%E3%82%B9%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%82%92%E4%BD%BF%E3%81%86
doc
https://next-auth.js.org/configuration/callbacks
> 295 backendから受け取ったjwtをnext-auth経由でsessionにsetできるようにしてあげた

- frontend/src/features/game/Game.tsx
- frontend/src/features/game/Types.ts
#309 から
やっぱり弾き返さない棒にした
- カーソルキー上下で動く無敵の棒を２つくった
- 2つの棒はとりあえず一緒に動く
- key入力のハンドル
- [addEventListener](https://developer.mozilla.org/ja/docs/Web/API/EventTarget/addEventListener#%E6%A7%8B%E6%96%87)
キーの名前が[ブラウザによって違う](https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#navigation_keys)らしい
https://github.com/s-xix98/trc-prot/blob/2545ab1ffd7ab105fc389c834ffc593024f4da56/frontend/src/features/game/Game.tsx#L114-L115
> 298 ゲームに触れるものすべてを弾き返す最強の棒を追加する

- frontend/src/features/game/Game.tsx
- frontend/src/features/game/Types.ts
> 310 左右の壁の衝突判定削除と棒の衝突判定追加

- backend/src/app.module.ts
- backend/src/auth/auth.controller.spec.ts
- backend/src/auth/auth.controller.ts
- backend/src/auth/auth.module.ts
- backend/src/auth/auth.service.spec.ts
- backend/src/auth/auth.service.ts
auth moduleを自動生成した
provider-login, email password loginを作る予定
> auth moduleの自動生成

- frontend/src/features/terminal/TerminalOutput.tsx
- keyを設定してなくてreactがブラウザコンソールでエラー吐いてたので修正
> keyを設定してなくてreactがブラウザコンソールでエラー吐いてたので修正

- backend/prisma/schema.prisma
> schema.prsmaのfmtした

- frontend/src/features/game/Game.tsx
> 357 続左右の壁の衝突判定削除と棒の衝突判定追加

- frontend/src/features/game/Game.tsx
- paddleの開始位置を真ん中にした
- 定数周りを 軽くリファクタ
> 366 game paddleの初期位置真ん中にする

- docker-compose.yml
- frontend/Makefile
- frontend/docker-entrypoint.sh
- frontend/package.json
- コマンドの整理
- `docker-entrypoint.sh` を作成
> 391 front docker-entrypoint.sh を作成

- backend/Makefile
- backend/docker-entrypoint.sh
- docker-compose.yml
- コマンドの整理
- `docker-entrypoint.sh` を作成
> 393 back docker-entrypoint.sh を作成

- frontend/src/App.tsx
- frontend/src/features/chat/components/Chat.tsx
- frontend/src/features/chat/components/ChatChannelArea.tsx
- frontend/src/features/chat/components/ChatChannelCreateModal.tsx
- frontend/src/features/chat/components/ChatInput.tsx
- frontend/src/features/chat/components/ChatTalkAreaHeader.tsx
- frontend/src/features/user/components/User.tsx
- frontend/src/stores/jotai.ts
- jotaiの変数移動
- Appに置いとくのは、もうやめよう、、、
> 395 jotaiの変数移動

- backend/package-lock.json
- backend/package.json
- backend/prisma/schema.prisma
- backend/prisma/seed.ts
- backend/src/auth/auth.service.spec.ts
- backend/src/auth/auth.service.ts
お待たせしました！！！！！！
ついにhash化しました！！！！
第二引数のsaltRounds分の　2^n回hash化が繰り返されるらしい
これだと2^10分hash化されるみたいよくわからん
```
bcrypt.hash(dto.hashedPassword, 10);
```
比較
```
bcrypt.compare(dto.hashedPassword, user.hashedPassword);
```
install cmd
```
npm i bcrypt
npm i -D @types/bcrypt
```
dbの中身確認すればhash化できてるか確認できる
この辺みました
https://zenn.dev/kisihara_c/books/nest-officialdoc-jp/viewer/security-encryptionandhashing#ハッシュ化
doc
https://www.npmjs.com/package/bcrypt
> 405 pwをhash化する

- backend/package-lock.json
> npm i した時順番が変わって面倒なので

- backend/Makefile
- backend/docker-entrypoint.sh
- backendのsetupをsetupとsetup-dbに分割
> backendのsetupをsetupとsetup-dbに分割

- frontend/.prettierignore
- fmt で storybook-static ディレクトリを対象外に
> prettierignore add storybook-static

- Makefile
> .githubディレクトリの中もfmt

- Makefile
- コンテナが動いてなくても fmt, lint できるように
- `npm i` されてないと、動かない時あるかもー、 (docker イメージの更新してない時)
> コンテナが動いてなくても fmt, lint できるように

- .github/workflows/storybook-test.yml
- .github/workflows/storybook-update.yml
- バックグラウンドでplaywrightをInstallしつつ、storybook-build するようにした
> ci storybook の速度改善

- backend/src/chat/chat.gateway.ts
- frontend/src/features/chat/components/ChatChannelArea.tsx
- frontend/src/features/chat/types/joinChannelDto.ts
#438　から
チャンネルをクリックしたらそのチャンネルに入れますはい
createしたchannelでチャットできますはい
チャット履歴がある状態で他のチャンネルをクリックすると履歴が残ったまま変わってしまいますはい
> 439 channel join機能を作った

- frontend/src/App.stories.tsx
- frontend/src/app/login/page.stories.tsx
- frontend/src/app/page.stories.tsx
- storybook meta のところに next の 設定書けるみたいだから移動した
> storybook meta のところに next の 設定書けるみたいだから移動した

- frontend/src/hooks/useSessionAxios.ts
pathだけつければいいようにした
```
const a = useSessionAxios();
a.get('/');
```
> sessionAxisにデフォルトのurlをつけた

- backend/src/game/game-constants.ts
- backend/src/game/logic/game-logic.ts
> 514 game 壁の衝突判定を追加

- frontend/src/features/user/components/LoginForm.stories.tsx
- frontend/src/features/user/components/SignUpForm.stories.tsx
- ci が落ちることあるので ちょい sleep 追加ます
> ci が落ちることあるので ちょい sleep 追加ます

- frontend/src/features/game/Game.tsx
- frontend/src/features/game/Types.ts
- frontend/src/features/game/dto/GameDto.ts
useSocketのコールバックが肥大化してきたので整理した
> refactor: 各オブジェクトの生成を関数に切り出した

- backend/src/game/logic/game-logic.ts
> ボールどっかいったらgameがリスタートするようになった

- backend/src/game/game-constants.ts
https://typescriptbook.jp/reference/values-types-variables/const-assertion
再帰的にconstにする新技
> 真の定数を手に入れた！

- backend/src/game/game-constants.ts
- backend/src/game/logic/game-logic.ts
上下左右の端を0,1でハードコードしてたのを定数定義して修正した、それだけのこと、、、
> 586 マジックナンバーなおす

- frontend/src/features/game/Game.tsx
> 605 game描画の細かい修正

- frontend/package-lock.json
- frontend/package.json
- frontend/scripts/install_dependencies.sh
- frontend/src/app/layout.tsx
- frontend/src/features/terminal/Terminal.tsx
- mui の ところに書いてあった `notistack` ってやつを使った
- [Notistack](https://notistack.com/)
- `n` って打ったら、適当に通知出るはず
> 右上に通知出せるようにした

- .github/workflows/e2e-test.yml
- frontend build と playwright install 同時に実行
- playwright install 遅いますぴえん
> frontend build と playwright install 同時に実行

- backend/src/chat/chat.controller.ts
- backend/src/chat/chat.service.spec.ts
- backend/src/chat/chat.service.ts
- backend/src/user/types/userInfo.ts
roomMember listを取得できるようにした
```
エンドポイント
@Get('rooms/:id/members')
```
> 658 roommemberを取得するエンドポイントを作る

- backend/src/user/user.gateway.spec.ts
- backend/src/user/user.gateway.ts
消した後にfrontのリストを更新する予定
```
// イベント名
@SubscribeMessage('unfriendUser')
@SubscribeMessage('unblockUser')
```
> 677 フレンドの削除, blockの削除を作る

- backend/src/game/logic/game-logic.ts
- frontend/src/features/game/Game.tsx
適当に3ポイント先取で勝敗を扱えるようにした
二人プレイじゃないから、一旦winしかできないけど
> 683 [Game] ゲームオーバーのハンドリング

- backend/prisma/schema.prisma
プレイヤーのランキングとか作る用
index貼ってみた
[単一インデックスを貼る例](https://www.prisma.io/docs/reference/api-reference/prisma-schema-reference#define-a-single-column-index)
> [DB] レーティング用のスキーマ作った

- backend/src/game/game.gateway.ts
- backend/src/game/logic/game-logic.ts
- frontend/src/features/game/Game.tsx
- 二人プレイできるようにした
- 友達がいない人でも一人二役であそべる
- めんどくさいから全部べた書きした、あとでリファクタリングするかもだけどしないかも
> 657 [Game] 二人プレイ

- backend/src/game/logic/game-logic.ts
> 691 [Game] refactor

- frontend/src/features/game/Game.tsx
> fix: 描画関数の呼び出し順に依存して色が変わってそうだったのを修正

- frontend/src/features/game/Game.tsx
> 699 [Game] canvas描画の微調整

- backend/prisma/schema.prisma
> [DB] 対戦履歴用のテーブル

- backend/src/game/logic/game-logic.ts
- frontend/src/features/game/Draw.ts
- frontend/src/features/game/Factory.ts
- frontend/src/features/game/Game.tsx
> 701 [Game] refactor2

- frontend/src/features/game/Matching.tsx
> 705 game 変なボタンあるのを消す

- frontend/src/App.tsx
- frontend/src/features/chat/api/createChannel.ts
- frontend/src/features/chat/api/joinChannel.ts
- frontend/src/features/chat/api/sendMsg.ts
- frontend/src/features/chat/components/ChatChannelCreateModal.tsx
- frontend/src/features/chat/components/ChatTalkArea.tsx
- frontend/src/features/game/Game.tsx
- frontend/src/features/game/Matching.tsx
- frontend/src/features/terminal/Terminal.tsx
- frontend/src/features/user/api/blockRequestSender.ts
- frontend/src/features/user/api/friendRequestSender.ts
- frontend/src/hooks/useSession.ts
- frontend/src/hooks/useSocket.ts
- frontend/src/socket.ts
- frontend/src/stores/jotai.ts
userIdとsocketをマップするために実装
session時にio()を呼ぶようにした
as huga -> as piyo などのの切り替え時に新しくsocketをset,socket.discconect()する必要がある、401時のsocket.dissconect()が未実装、誰かがやります。
by wyohei
> 687 login時 or sessionある状態の時にsocketを繋げる 2

- backend/src/game/logic/game-logic.ts
> [Game] プレイヤー２が有利すぎたのでプレイヤー１にもチャンスを与えることにした

- frontend/src/app/page.stories.tsx
- storybook の chat 周りのテストをコメントアウト
- e2e で この辺のやつはカバーできてるはず
- socketが、undef になって ルームの取得がうまくできてないみたい
> fix storybook test

- backend/src/auth/auth.module.ts
- backend/src/auth/auth.service.spec.ts
- backend/src/auth/auth.service.ts
- backend/src/chat/chat.gateway.spec.ts
- backend/src/chat/chat.service.spec.ts
- backend/src/test/test.module.ts
- backend/src/test/test.service.ts
- backend/src/user/user.gateway.spec.ts
- backend/src/user/user.service.spec.ts
- backend/src/wsocket/wsocket.gateway.ts
- backend/src/wsocket/wsocket.module.ts
とりあえず接続時にsocket userid と useridとsocketをマップさせた
> 717 useridとsocketをマップする

- backend/src/game/game.controller.ts
- backend/src/game/game.module.ts
- backend/src/game/game.service.spec.ts
- backend/src/game/game.service.ts
- backend/src/game/types.d.ts
`{userid, username, rating}`をレート高い順に配列で返すAPI作った
> 721 ランキング取得できるようにする

- backend/src/auth/auth.service.ts
- backend/src/user/user.gateway.spec.ts
- backend/src/user/user.gateway.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.ts
- backend/src/wsocket/wsocket.gateway.ts
接続時に以下を返す
```
client.emit('blockUsers', blockUsers);
client.emit('friends', friends);
client.emit('friendRequests', friendRequests);
```
> 725 socket接続時にfriendshipをfrontに返す

- backend/src/game/game.controller.ts
- backend/src/game/game.gateway.spec.ts
- backend/src/game/game.gateway.ts
- backend/src/game/game.module.ts
- backend/src/game/game.service.spec.ts
- Wsocketでのuser-socketマッピングで、gameが動かなくなってた問題を修正
- Game固有のマッピングをWsocketで置き換えた
> 734 [Game] 新しいユーザーとソケットのマッピング方式に対応

- backend/src/game/game.gateway.ts
> 740 [Game] refactor

- frontend/src/App.tsx
- frontend/src/features/chat/api/createChannel.ts
- frontend/src/features/chat/api/joinChannel.ts
- frontend/src/features/chat/api/sendMsg.ts
- frontend/src/features/chat/components/Chat.tsx
- frontend/src/features/game/Matching.tsx
- frontend/src/features/user/api/blockRequestSender.ts
- frontend/src/features/user/api/friendRequestSender.ts
- frontend/src/features/user/components/UserProfile.tsx
- frontend/src/hooks/useCurrentUser.ts
- frontend/src/hooks/useLogin.ts
- userinfoAtomを直接 触ってるところを useCurrentuserを使用するように
- userInfo だと どのユーザーわかりずらいので、currentUserInfo にした
> userinfoAtomを直接 触ってるところを useCurrentuserを使用するように

- backend/src/wsocket/wsocket.gateway.ts
- frontend/src/app/layout.tsx
> tokenがないまたはverify失敗時にlogoutイベントを発火させるようにした

- frontend/src/app/layout.tsx
- frontend/src/features/chat/components/Chat.tsx
- frontend/src/features/chat/types/chatChannelDto.ts
- frontend/src/features/terminal/Terminal.tsx
- frontend/src/features/user/api/userLogin.ts
- frontend/src/features/user/types/UserDto.ts
- frontend/src/hooks/useCurrentUser.ts
- frontend/src/stores/jotai.ts
- フレンドリスト等の状態を保持するように
- カレントのユーザー情報をまとめたかったので、
- userInfoAtom
- channelListAtom を駆逐
- Atom 討伐数 2
> フレンドリスト等の状態を保持するように

- frontend/src/features/chat/api/roomHistory.ts
- frontend/src/features/chat/api/roomMembers.ts
- frontend/src/features/chat/components/ChannelSearchModal.tsx
- frontend/src/features/chat/types/MessageDto.ts
- frontend/src/features/user/api/userLogin.ts
- frontend/src/features/user/components/Search.tsx
- frontend/src/features/user/types/UserDto.ts
- frontend/src/hooks/useSearch.ts
- frontend/src/hooks/useSessionAxios.ts
- axiosの型で嘘つかれるので、型チェックするゲッターを作成
- useEffectの中で、customAxiosGetter を使う際に、依存関係にonSucessCallbackを含める必要があるが、
- その際 state を更新する場合、useCallbackを使う必要あるので注意
> 嘘つかれるので安全に取得できるaxiosゲッター的なものを作ってみる

- backend/src/game/dto/Api.d.ts
- backend/src/game/game.controller.ts
- backend/src/game/logic/game-logic.ts
- backend/src/game/types.d.ts
リファクタでマッチングテーブル切り出そうと思ったけど
思ったより実装量あるから分けることにした
> 792 [Game] refactor

- frontend/src/features/user/components/UserProfile.tsx
- frontend/src/hooks/useUserProfileModal.ts
- User profile出すやつのロジック分離
- 他でも使うので、使いやすくー
> User profile出すやつのロジック分離

- backend/src/chat/chat.gateway.ts
- backend/src/user/user.gateway.ts
> 例外でそうなところをtry catchで囲んだ

- backend/src/chat/chat.gateway.ts
- backend/src/chat/dto/Channel.dto.ts
- frontend/src/App.tsx
とりあえず抜けるだけ
確認
./test
leaveボタン押す
joinedroom[0]を抜ける
> 776 chat抜けるを作る

- backend/src/game/game.gateway.ts
- backend/src/game/game.service.ts
- backend/src/game/types.d.ts
- backend/src/prisma/types.d.ts
game終了処理にトランザクション貼っただけ
プリクラを使ってみた
> 808 [Game] 終了時のdb処理にトランザクション貼る

- backend/src/chat/chat.controller.ts
- backend/src/chat/chat.gateway.ts
- backend/src/chat/chat.module.ts
- backend/src/user/dto/user.dto.ts
- backend/src/user/user.gateway.spec.ts
- backend/src/user/user.gateway.ts
- backend/src/user/user.module.ts
- backend/src/user/user.service.ts
- frontend/src/App.tsx
- frontend/src/hooks/useCurrentUser.ts
名前や画像を変更したuserのfriend, blockしてるuser, friendreq , chatを全て更新するようにした
> 778 username,imageを変更できるイベントを設置

- backend/src/game/game.gateway.ts
- backend/src/game/matching/matching-table.ts
- backend/src/game/matching/types.d.ts
inviteのマッチング作ると色々管理するものが増えそうなのでマッチング用の機能を切り出した
- #796 は分割してclose、前回からの変更点はほぼなし
- #809 からrebaseしてconflict直したり、無駄なコミットまとめただけ
> 795 [Game] マッチング用のクラス作る

- backend/prisma/schema.prisma
- backend/src/user/dto/user.dto.ts
> base64imageをstringに変更

- backend/src/game/matching/matching-table.ts
> refactor: typedefみたいな気分でstringをUserId型で置き換えた

- backend/src/chat/chat.service.ts
- backend/src/user/user.service.ts
userinfo返すやつにはimageをつけて返すようにした
> 844 userinfoに画像つける

- frontend/src/components/Elements/Input/Input.tsx
- frontend/src/features/terminal/Terminal.tsx
- test/src/user_action.py
- terminal の ユーザー名クリックしたら自分のユーザー情報表示できるように
> 866 terminal の ユーザー名クリックしたら自分のユーザー情報表示できるように

- backend/src/chat/chat.gateway.spec.ts
> たまにciで死ぬのを修正できたらいいな

- frontend/src/components/Elements/Modal/ModalView.tsx
> 面倒なのでとりあえず、modal view で overflow スクロールするように

- frontend/src/features/chat/components/ChannelInfo.tsx
- frontend/src/features/chat/components/ChannelSearchModal.tsx
- 検索結果のチャンネルもモーダル表示できるように
- 参加済みユーザーリストでユーザーもモーダル表示できるように
> モーダル表示できてなかった部分、モーダル表示できるように

- test/src/__main__.py
- test/src/playwright_runner.py
- test/src/test_basic.py
- test/src/test_chat.py
- test/src/test_login.py
- e2e test のリファクタ
- import 地獄解消
- ブラウザ出してテストする時のチカチカ解消
> e2e test リファクタ

- backend/src/user/user.gateway.ts
- フロント FriendRequests から block した時、FriendRequests のリストがちゃんと更新されなかったのでー
> 更新後にデータ送信するように修正

- backend/src/chat/chat.gateway.ts
- join チャンネルした時、参加済み チャンネルリストが更新されなかったので追加
> join した時に channle list 更新されなかったので追加

- backend/src/chat/chat.gateway.ts
- backend/src/chat/chat.service.ts
gatewayに直接書いてた実質boolean的な処理を関数に移動。
roomがないor userがいない場合の処理を全体的に追加
> 832 chatリファクタ+fix 2

- backend/src/chat/chat.gateway.spec.ts
- backend/src/chat/chat.gateway.ts
chatキックされたりbanされたuserのjoinedroomを更新する処理を追加.
socketRoomからleaveする処理も追加
ちょっとリファクタ
> 836 chatTODOや未実装のところ実装

- test/src/playwright_runner.py
- test/src/test_many_user.py
> e2e テスト マルチスレッドで同期とれるように

- backend/src/chat/chat.gateway.ts
- backend/src/chat/dto/Channel.dto.ts
```@SubscribeMessage('rejectChatRoomInvitation') ```
dbから削除して招待更新するようにした
> 803 chat reject を作る

- frontend/src/features/chat/api/acceptInvite.ts
- frontend/src/features/chat/components/ChannelInfo.tsx
- frontend/src/features/chat/types/InviteChatRoomDto.ts
- frontend/src/hooks/useCurrentUser.ts
> 901 フロント acceptinvite つくる

- backend/prisma/schema.prisma
- backend/src/user/user.gateway.ts
- backend/src/user/user.service.ts
connect -> onlineに変更しfriendに送る
discconect->offlineに変更しfriendに送る
> 777 userの現在の状態をつける

- backend/src/chat/chat.service.ts
> 889 roomにすでに参加してたときの処理を追加

- backend/src/chat/chat.gateway.spec.ts
- backend/src/chat/chat.gateway.ts
- backend/src/chat/chat.service.spec.ts
- backend/src/chat/chat.service.ts
- backend/src/chat/dto/Channel.dto.ts
- backend/src/chat/dto/message.dto.ts
- backend/src/user/dto/friendship.dto.ts
- backend/src/user/user.gateway.spec.ts
- backend/src/user/user.gateway.ts
jwtからuserIdを取得できるから不要なuserIdを削除した
> 842 backend fix リファクタ 不要なuseridを消す

- backend/src/chat/chat.gateway.ts
- backend/src/chat/chat.service.ts
- backend/src/chat/dto/Channel.dto.ts
chatroomのupdateを作った
pwdのif文がきもい
> 904 chatroom update作る

- frontend/src/features/chat/api/createChannel.ts
- frontend/src/features/chat/api/inviteChannel.ts
- frontend/src/features/chat/api/joinChannel.ts
- frontend/src/features/chat/api/sendMsg.ts
- frontend/src/features/chat/components/ChatChannelCreateModal.tsx
- frontend/src/features/chat/types/CreateChannelDto.ts
- frontend/src/features/chat/types/MessageDto.ts
- frontend/src/features/chat/types/joinChannelDto.ts
- frontend/src/features/user/api/blockRequestSender.ts
- frontend/src/features/user/api/friendRequestSender.ts
- frontend/src/features/user/api/unblockRequestSender.ts
- frontend/src/features/user/types/FriendshipDto.ts
> オレオレ userid 撲滅した

- backend/src/chat/chat.gateway.ts
- backend/src/chat/dto/Channel.dto.ts
kickでended使わないからKickRoomMemberの型つけた
> 924 kickroommemberの型をつける

- backend/src/chat/chat.gateway.ts
- frontend/src/features/chat/api/muteRoomMember.ts
- frontend/src/features/chat/components/ChatRoomMembers.tsx
- 未知のエンドポイントと遭遇した
- バックエンドおかしかったので直してあげた
> 934 muteも作るらしいので

- backend/src/chat/chat.service.ts
- frontend/src/features/chat/components/ChannelInfo.stories.tsx
- frontend/src/features/chat/components/ChatTalkArea.stories.tsx
- frontend/src/features/chat/components/ChatTalkAreaHeader.stories.tsx
- frontend/src/features/chat/types/chatChannelDto.ts
フロントに優しいbackendだからisPrivate, hasPasswordのbooleanをつけた
> 940 返すroomにis privateとhasedpwdをつける

- frontend/src/features/chat/components/ChatHistory.tsx
- ブロックしてるユーザーのメッセージは `--- this is block User Msg ---` と出力されるようにした
> ブロックしてるユーザーのメッセージ表示しないように

- backend/src/game/game-constants.ts
- backend/src/game/game.gateway.ts
- frontend/src/features/game/Factory.ts
- frontend/src/features/game/Game.tsx
- frontend/src/features/game/Types.ts
横長にした
バックエンドから比率を送信してフロント側でスケールさせるようにした
> 945 game 縦横比を変える

- backend/src/game/game-room.ts
- backend/src/game/game.gateway.ts
- backend/src/game/logic/game-logic.ts
- frontend/src/features/game/Game.tsx
- frontend/src/features/game/Types.ts
> 959 game 敵の名前をフロントに渡す

- backend/src/game/logic/game-logic.ts
- backend/src/game/types.d.ts
> 880 game めり込みなおす

- backend/src/game/game.gateway.ts
- backend/src/user/user.gateway.ts
- backend/src/user/user.module.ts
> 1006 game play状態表示

- backend/src/user/user.gateway.ts
- frontend/src/features/user/components/UserProfile.tsx
挙動はほぼ変わらんと思うけど一応GANME状態をONLINEで上書きすることがありそう
あとuserprofileにinvitegame複数あったのを消した気分
> ラッパーに置き換わってなかったのを修正
