s-xix98/trc-prot

- frontend/src/components/Layout/ContainerItem.tsx
- frontend/src/features/chat/ChatHistory.tsx
- 修正前
- 修正後
- ref
- [overflow-wrap - CSS: カスケーディングスタイルシート | MDN](https://developer.mozilla.org/ja/docs/Web/CSS/overflow-wrap)
> チャットに長文が来た時に表示が崩れないように修正

- frontend/Makefile
- frontend/package.json
- log/frontend-log.md
- `tsc --noEmit` を実行するルールを追加
- [特徴 | Vite](https://ja.vitejs.dev/guide/features.html)
> add noEmit target

- backend/package.json
- backend/prisma/user_seed.ts
- docker-compose.yml
- log/backend-log.md
”npx prisma db seed”でdbにデータを追加できるようにした。
↑のコマンドでdbに追加できるuserダミーデータを書いた。
docker起動時にdbにuserデータを入れるようにcomposeに↑のコマンドを追記した
参考にしたやつ
https://www.prisma.io/docs/guides/migrate/seed-database
> 64 testをやりやすくするためにdocker起動時にダミーユーザーをdbに追加した

- frontend/package.json
- backend の 方は デフォの lint がそもそも `--fix` オプション付いていたので、そこ含め 別プルリクで修正
> Eslint で 一つでも warning が あったら ci 通らないようにした

- docker-compose.yml
npm installがバックグラウンド実行されてたのでprismaの部分のみをバックグランドにした
> &までがバックグランドで実行されていてnpm installが実行されないので&の範囲を狭めた

- backend/prisma/schema.prisma
- backend/src/events/events.gateway.ts
- backend/src/events/events.module.ts
外部のmoduleが必要だったのでevents.gateway.tsの依存関係を管理するためにmoduleファイルを追加した
Userテーブルのidを引数に渡すとそのuserの過去のmsgを全て取得できるようにした
> 84 socket ioで個人のチャット履歴を返せるようにした

- frontend/src/features/chat/Chat.tsx
- frontend/src/features/chat/ChatChannelArea.tsx
- frontend/src/features/chat/ChatHistory.tsx
- frontend/src/features/chat/ChatInput.tsx
- frontend/src/features/chat/ChatTalkArea.tsx
- frontend/src/features/chat/ChatTalkAreaHeader.tsx
- frontend/tsconfig.json
- frontend/vite.config.ts
- log/frontend-log.md
- import で alias を使用して import できるようにした
- `import { Container } from '../../components/Layout/Container';` 
- ->
- `import { Container } from '@/components/Layout/Container';`
- 下記 記事 などで `eslint-import-resolver-typescript` が紹介されてたが
- 特にメリットもよくわからんかったし、今回は特に問題出てないので一旦無視
- [Vite+React+TypeScript+EsLintで、Importパスにエイリアスを使うためにハマったこと](https://zenn.dev/longbridge/articles/5e33ff1a625158)
- よくわからんし、問題ないので放置
- [TypeScript / JavaScript の import を自動でソートする - Sansan Tech Blog](https://buildersbox.corp-sansan.com/entry/2021/05/28/110000)
> 111 front import パス の 改善

- .github/workflows/check-code-style.yml
- .github/workflows/check-lint.yml
- .github/workflows/storybook-test.yml
- frontend, backend の node_modules を キャッシュ化
- プルリク ごとには install が走る
- `restore-keys` を 設定すれば 走らないようになる？
- まだ勉強中、とりあえず これで問題なく動く
- このブランチで実験
- リンク先の ✅ とか ❌ から それぞれの ワークフローにかかってる時間見れるマス
- https://github.com/s-xix98/trc-prot/pull/117/commits
- [他のブランチからでも キャッシュが有効に使えているかのテストます](https://github.com/s-xix98/trc-prot/pull/117/commits/64e9b8021681aa49177281abc3b6184c427b2d36) -> 新しいプルリクだと時間かかる
- [他のブランチからの時はキャッシュが効いてない感じ？](https://github.com/s-xix98/trc-prot/pull/117/commits/623ec023f288e096c1a989bf985df560a5fa8776) -> キャッシュで インストールが早い
- [ハッシュが 変わって フロント は 再インストールされるはず](https://github.com/s-xix98/trc-prot/pull/117/commits/36299a860faf0100be953d7022b872642ab151c0) -> key に 使ってるハッシュ変わって再インストール
ref
- [依存関係をキャッシュしてワークフローのスピードを上げる - GitHub Docs](https://docs.github.com/ja/actions/using-workflows/cachin …
> 115 GitHub action の キャッシュを 修正

- .github/workflows/storybook-test.yml
- マージされてから
---
- storybook-test の 実行が遅かったので 必要なものの install を キャッシュして 高速化
- プルリクごとには install し直すようになってるので、最初は遅います
> 109 storybook test の GitHub action の 実行に時間かかってるので 早くする

- backend/Makefile
- backend/package-lock.json
- backend/package.json
- backend/src/post-message/post-message.service.spec.ts
- backend/src/post-message/post-message.service.ts
- log/backend-log.md
jestはテストするファイルのimportを絶対パスで使用するにはpackage.jsonをいじらないといけなさそうなので,相対パスに変更した（問題なければ全部かえる）
`import {UserService} src/user/user.service.ts` -> `import {UserService} ../user/user.service.ts `
post-messageのエンドポイントのmockテスト作成。
dbを操作するPrismaServiceをmockしてるけどdbを使うならテストに変える。
make testでjestを走らせるようにした　
> 108 post messageエンドポイントのテストを作る

- backend/.devcontainer.json
- backend/Dockerfile
- docker-compose.yml
- frontend/.devcontainer.json
- frontend/Dockerfile
- node_modules を docker コンテナ内に インストール
- とりあえず 下の記事読んで
- [VSCode&Docker Volumeにおけるnode_modules問題を解決する](https://zenn.dev/yumemi_inc/articles/3d327557af3554)
- node_modules ディレクトリのみ コンテナと 同期しない
- また docker ビルド時に npm i するようにしたので、再ビルドする時 時間かかる時あるかも。
- node_modules を ホスト側に なくても 動くが、vscode が node_modules を 参照できずに エラーとか出る
- ローカルでも front, back で `npm i` する 
or 
- vscode の devcontainer 使う
- 一応 設定したが、front, back が あるので 正直 あんまり使いやすくないかも。
- [Connect to multiple containers](https://code.visualstudio.com/remote/advancedcontainers/connect-multiple-containers)
> 135 node modules を docker コンテナ に

- backend/src/user/user.controller.ts
- backend/src/user/user.service.ts
ユーザーの入力でlogin,signup失敗時のエラーコードは403にした
他のエラーはデフォルトで５００。
https://docs.nestjs.com/exception-filters
login成功時は200を返すようにした
P2002
https://www.prisma.io/docs/reference/api-reference/error-reference
> 132 login成功時、signup成功時にuserの情報を返すようにした

- frontend/src/components/Layout/ContainerItem.tsx
- ContainerItem css display の デフォルト を inline に 設定
- 元の auto なんて パラメータは 存在しなかったようだ ( ; ; )
> ContainerItem css display の デフォルト を inline に 設定

- backend/src/events/events.gateway.spec.ts
- backend/src/events/events.gateway.ts
- backend/src/post-message/post-message.controller.spec.ts
- backend/src/prisma/prisma.service.spec.ts
- backend/src/test/test.module.ts
- backend/src/user/user.controller.spec.ts
- backend/src/user/user.service.spec.ts
- backend/src/user/user.service.ts
同じ入力を何度もしないために、全てのテストファイルに依存しているproviderをexportするだけのTestmoduleを作った.
依存関係やimoprtのパスでエラーが出てたから修正した
追記
import { PrismaService } from 'src/prisma/prisma.service';
↓に変更
import { PrismaService } from '../prisma/prisma.service';
#154　をした
cd backend && make test　で確認できる
> 154 backendのテストが依存関係やimportパスでfailしてるから修正する

- .github/workflows/check-build.yml
- .github/workflows/check-code-style.yml
- .github/workflows/check-lint.yml
- .github/workflows/storybook-test.yml
- github action の on に main push を 追加
- main に 変更があるたびに 再実行されるようになったはず
- ref
- [スクリプトを使ってランナーでコードをテストする - GitHub Docs](https://docs.github.com/ja/actions/examples/using-scripts-to-test-your-code-on-a-runner)
> main に 変更が あった際に 再度 github action が 実行されるようにした

- backend/.env
- docker-compose.yml
- とりあえず、docker compose で起動された場合と そうでない場合で分岐
- そもそも、`.env` を git 管理してるのも よくないから ファイル名変えたりするます
- #183 イシュー立てたます
> DATABASE_URL を 実行環境によって 変わるようにした

- .github/workflows/check-build.yml
PrismaClientのメソッドがないとbuild時にエラーが出る。
ciのcheck-buildで現在のスキーマに合わせてPrismaClientを生成するようにした。
> ciのcheck-buildでPrismaClientを生成するコマンドを追加した

- frontend/package.json
- storybookの出力が大量に出ているので、`--quiet` オプションをつけて、あまり出ないようにした
- 参考リンク
- [CLI options](https://storybook.js.org/docs/react/api/cli-options)
> storybookの出力が大量に出ているのを、あまり出ないように

- .github/workflows/storybook-test.yml
- ciでバージョン変わった時 落ちる問題が発生したので対応
> playwrightのcacheのkeyにplaywrightのversionを追加

- .github/workflows/storybook-test.yml
- ci で cache している ディレクトリは `~/.cache/ms-playwright` だけ
- `npx playwright install-deps` で インストールされるものは、この場所以外にインストールされてる
- 上記のため、毎回 `npx playwright install-deps` を実行するようにした
> playwright install-deps は毎回実行するようにした

- docker-compose.yml
- next js で ホットリロードが効くように
- 環境変数 WATCHPACK_POLLING を true に設定
- パッとリファレンス見つけられなかったます
- 多分 watchpack の WATCHPACK_POLLING を同じ
- [watchpack/README.md at main · webpack/watchpack · GitHub](https://github.com/webpack/watchpack/blob/main/README.md)
- 参考にした記事
- [next.js の開発環境を Docker で構築しようとした時にハマったことまとめ | 経験知](https://keikenchi.com/build-nextjs-development-environment-with-docker)
> next js で ホットリロードが効くように

- frontend/.storybook/test-runner.js
- 指定したケースで、コンポーネントでは、スナップショットをとらないようにした
- 動きのあるコンポーネントでdiff発生してテスト落ちるので
- storybook
- 無効化したいケースは `SkipSnapshotTest` の文字列を含める
- `export const Basic: Story = {};` -> `export const BasicSkipSnapshotTest: Story = {};`
> 指定したケースで、コンポーネントでは、スナップショットをとらないようにする

- frontend/scripts/check_storybook_file.sh
nameオプションは"/"を含むとマッチしないので、まったく意味がないから削除
> findの不要なオプションを削除

- backend/Dockerfile
- frontend/Dockerfile
node19は長期サポートじゃない
node20は現在ライブラリをnode20に合わせる期間でバグが多いらしい
なら１８だよね
https://nodejs.dev/en/about/releases/
> nodeのバージョンを18にした

- backend/prisma/schema.prisma
- backend/prisma/seed.ts
authでログインしたユーザーの情報を保存するテーブルを作った
アクセストークンでとってくるidとprovider名の組み合わせでuniqueとして判定するようにした
providerテーブルはテーブルで管理できるようにした
providerを増やしてもレコード挿入とfrontの変更だけで済む
現在42とgoogleを使ってるのでseedで入れた
> 326 auth用のテーブルを作る

- frontend/.storybook/test-runner.js
- モーションのあるコンポーネントだと、diffが発生するので少し待ってからスクショ撮るようにした
> モーションのあるコンポーネントだと、diffが発生するので少し待ってからスクショ撮るようにした

- backend/Dockerfile
- frontend/Dockerfile
debianの最新バージョン 12 がリリースされた
https://www.debian.org/News/2023/20230610
from node:18はdebianの最新バージョンになる
playwrightがdebian 12のサポートしてなくてビルドに失敗した
debian12 -> 11に変更した
> buildでエラーが出てたのでdockerimage osのバージョンを変更した

- backend/src/game/logic/game-logic.ts
衝突時に速度反転させてただけだったのを少し真面目に計算するようにした
今までは現フレームでのボール位置を起点に逆方向に座標移動させてただけ
ちゃんと衝突位置を起点に、残りの移動距離を動かすように変更した
例えば、速度が1Fに画面半分で、今ボールの位置が画面中心、向きが真上だとしたら
- 前　上の壁の衝突判定が発生して速度が反転、**ボールの位置**から計算して画面半分を下に移動 -> 下の壁あたりに移動
- 今　上の壁の衝突判定が発生して速度が反転、画面半分上に進んで、残り移動距離が0で、上の壁あたりで終わり
> 宇宙の法則に従うことにした

- backend/src/game/game.gateway.ts
- 二人プレイに備えて複数のクライアントをgameインスタンスに渡してコンストラクトするようにした
- ディスコネ時の削除の処理は適当に強制終了、後で考える
> 686 [Game] マッチングしたuserにgameのインスタンスをマップする

- backend/src/game/logic/game-logic.ts
- frontend/src/features/game/Game.tsx
- 自分がどっちのパドル操作するかバックエンドから通知されるようにした
- バックとフロント共通の何かを定義するのがめんどかったのと、条件分岐増えるから、イベントリスナで分けたけど、データの送り方で分けた方がいいか？
- 表示は適当
> 695 [Game] プレイヤーの左右を表示
